### ISSUE TITLE
Eliminar comentarios

### ISSUE THREAD

**Issue by NicoGonzalez94** [GustavoRodriguez160205/proyecto#27]
Buenas! como va? encontre algunos comentarios en el codigo,

![image](https://github.com/user-attachments/assets/6399fb74-1c2c-4467-9b98-772f5310a4a7)

Recuerden, los comentarios no estan vistos como una buena practica , pero en si el codigo comentado es mucho menos aceptado.

Cualquier cosita podes contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by CLAUDIOTOLEDO252208** [comment]
Hola buen dia! Observsciones corregida.
