### ISSUE TITLE
Espacio sin contenido

### ISSUE THREAD

**Issue by NicoGonzalez94** [GustavoRodriguez160205/proyecto#28]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• No encontrar un espacio en blanco entre el contenido de la pagina y el footer.

## Resultado actual

• Se encuentra un espacio en blanco sin contenido.

## Captura

![image](https://github.com/user-attachments/assets/05f2807c-9b6b-410e-8437-0fa245c10768)

## Posible solucion

•Quitar margin top 15 rem*

![image](https://github.com/user-attachments/assets/f4822af1-d4b8-40d4-9be9-7a278999c8db)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by CLAUDIOTOLEDO252208** [comment]
Hola buen dia! Observacion corregida
