### ISSUE TITLE
Botones sin accion

### ISSUE THREAD

**Issue by NicoGonzalez94** [GustavoRodriguez160205/proyecto#29]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Que los botones redirijan a dicho sitio o una page 404.

## Resultado actual

• Los botones no cumplen ninguna funcion.

## Captura

![image](https://github.com/user-attachments/assets/41caaad3-b1e1-4353-9711-721c54a0d38b)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by CLAUDIOTOLEDO252208** [comment]
Hola buen dia! Observacion corregida
