### ISSUE TITLE
Canchas imagenes

### ISSUE THREAD

**Issue by NicoGonzalez94** [GustavoRodriguez160205/proyecto#30]
## Proceso

1. Ingrese a la pagina.
2. Quise ver las canchas disponibles.

## Resultado esperado

• Poder ver información de las canchas sin problemas.
• Al no cargar las imágenes, poder ver las etiquetas "alt" con su descripción.

## Resultado actual

• Las imagenes no se muestran correctamente.
• Etiquetas "alt" del carousel no tienen descripción.

## Captura

![image](https://github.com/user-attachments/assets/f9e08209-5164-4636-8798-c20fbfe8a336)
![image](https://github.com/user-attachments/assets/dc3fa78c-f03e-44d7-82b8-811966a238db)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by CLAUDIOTOLEDO252208** [comment]
Hola buen dia! Observacion corregida
