### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by NicoGonzalez94** [GustavoRodriguez160205/proyecto#31]
Buenas! Como va? Chicos necesito que resuelvan este error para poder continuar con la devolucion del proyecto
Este error puede ser el causante de varios errores mas.
Una vez resuelto puedo continuar con la devolucion.

![image](https://github.com/user-attachments/assets/3076d685-03bf-4dbf-a801-81f9808ceee0)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by NicoGonzalez94** [comment]
Buenas! Si de hecho es un error de netifly. netifly tiene una guia de como solucionarlo igualmente se las dejo por aqui. 
https://answers.netlify.com/t/support-guide-i-ve-deployed-my-site-but-i-still-see-page-not-found/125?utm_source=404page&utm_campaign=community_tracking

**Comment by CLAUDIOTOLEDO252208** [comment]
Hola! correccion realizada, gracias a la documentacion brindada.

**Comment by CLAUDIOTOLEDO252208** [comment]
[elclubfcsomosfutbolerosv2.netlify.app](https://elclubfcsomosfutbolerosv2.netlify.app/) direccion deploy app
