### ISSUE TITLE
Form contacto

### ISSUE THREAD

**Issue by NicoGonzalez94** [GustavoRodriguez160205/proyecto#33]
## Proceso

1. Ingrese a la pagina.
2. Quise hacer una consulta.

## Resultado esperado

• Que no se permita colocar numeros y signos en el nombre y apellido.
• Encontrar un max de caracteres a colocar en el mensaje.
• Que al en hacer click en enviar haya un modal o algo que me avise que mi consulta fue enviada.

## Resultado actual

• Se permite colocar numeros y signos en el nombre y apellido.
• No hay un max de caracteres a colocar.
• Al hacer click en enviar no hay nada que me avise que mi consulta fue enviada o si hubo algún error

## Captura

![image](https://github.com/user-attachments/assets/a5b008b7-fa73-4605-8a68-b278fa754360)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by CLAUDIOTOLEDO252208** [comment]
Hola! correcciones realizdas.
