### ISSUE TITLE
Servicios

### ISSUE THREAD

**Issue by NicoGonzalez94** [GustavoRodriguez160205/proyecto#35]
## Proceso

1. Ingrese a la pagina.
2. Me loguee con un usuario para poder ver los servicios ofrecidos.

## Resultado esperado

• Que una vez ya registrado e iniciado sesion pueda ver los servicios ofrecidos.

## Resultado actual

• Una vez ya registrado con un usuario me vuelve a solicitar registro para ver los servicios.

## Captura

![image](https://github.com/user-attachments/assets/9b728017-9f48-4559-bc8d-11eeaa2f696f)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by CLAUDIOTOLEDO252208** [comment]
Hola! correccion realizada
