### ISSUE TITLE
Datos por consola

### ISSUE THREAD

**Issue by NicoGonzalez94** [GustavoRodriguez160205/proyecto#37]
## Proceso

1. Ingrese a la pagina.
2. Me loguee con un usuario.

## Resultado esperado

• Que no se muestre información por consola.

## Resultado actual

• Al iniciar sesion se muestran datos del usuario por consola.

## Captura

![image](https://github.com/user-attachments/assets/1da3fed9-f4dc-491a-bf9f-107ef60aa880)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by NicoGonzalez94** [comment]
Una vez logueado al ingresar a "Canchas + Turnos" se visualiza mas informacion por consola.
![image](https://github.com/user-attachments/assets/8937aa6d-bb86-418e-9da8-f561eacc4758)

**Comment by NicoGonzalez94** [comment]
Lo mismo sucede al ingresar a "Tienda+ Ecommerce"
![image](https://github.com/user-attachments/assets/091740a2-4af3-4a0c-a467-5844b8ca9486)

**Comment by CLAUDIOTOLEDO252208** [comment]
Hola buenas! correciones relizadas
